version: '3.8'
# docker-compose.yml for RAG application with Qdrant

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
    # mounting a volume for Qdrant data persistence
      - qdrant_data:/qdrant/storage
    # restart policy to ensure Qdrant is always running
    restart: unless-stopped

  app:
  # building in the current directory
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
      - ./Data:/app/Data
    environment:
      - MODEL_PATH=/app/model/mistral-7b-instruct-v0.1.Q4_K_M.gguf
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    restart: unless-stopped
    command: uvicorn rag:app --host 0.0.0.0 --port 8000

volumes:
# to retain Qdrant data across container restarts
  qdrant_data:
